apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-scripts
data:
  init.sql: |
    SELECT 'CREATE DATABASE todolist' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'todolist');
    CREATE TABLE IF NOT EXISTS todo (
      todo_id SERIAL PRIMARY KEY,
      description VARCHAR(255) NOT NULL);