apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: {{ .Values.image }}
          ports:
            - containerPort: 5050
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: S3_BUCKET
              value: {{ .Values.bucket }}
